import type { Personnel, Activity } from './types';

export const MOCK_PERSONNEL: Personnel[] = [
  {
    id: 'OPS-4291',
    name: 'Marcus Jensen',
    role: 'Technical Lead',
    site: 'Singapore Site A',
    crew: 'Shift Alpha',
    rotationStart: 'May 01, 2026',
    rotationEnd: 'May 15, 2026',
    status: 'on-duty',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    ticketStatus: 'Received',
  },
  {
    id: 'OPS-8821',
    name: 'Elena Rodriguez',
    role: 'Safety Crew',
    site: 'Dubai Site B',
    crew: 'Tech Crew',
    rotationStart: 'May 11, 2026',
    rotationEnd: 'May 25, 2026',
    status: 'on-duty',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    ticketStatus: 'Requested',
  },
  {
    id: 'OPS-1140',
    name: 'Chen Wei',
    role: 'Maintenance Specialist',
    site: 'Rotterdam Base',
    crew: 'Maintenance Crew',
    rotationStart: 'Apr 20, 2026',
    rotationEnd: 'May 04, 2026',
    status: 'off-duty',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&h=150&fit=crop',
    ticketStatus: 'Not Received',
  },
  {
    id: 'OPS-6632',
    name: 'Sarah Miller',
    role: 'Site Manager',
    site: 'Singapore Site A',
    crew: 'Shift Beta',
    rotationStart: 'May 05, 2026',
    rotationEnd: 'Jun 01, 2026',
    status: 'on-duty',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop',
    ticketStatus: 'Received',
  },
  {
    id: 'OPS-2234',
    name: 'David Thompson',
    role: 'Drilling Engineer',
    site: 'Dubai Site B',
    crew: 'Tech Crew',
    rotationStart: 'May 10, 2026',
    rotationEnd: 'May 24, 2026',
    status: 'on-duty',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
    ticketStatus: 'Requested',
  },
  {
    id: 'OPS-9912',
    name: 'Yuki Tanaka',
    role: 'Logistics Coord',
    site: 'Rotterdam Base',
    crew: 'Support Team',
    rotationStart: 'Jun 15, 2026',
    rotationEnd: 'Jun 30, 2026',
    status: 'off-duty',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    ticketStatus: 'Requested',
  },
  {
    id: 'OPS-5541',
    name: 'Robert Brown',
    role: 'Safety Officer',
    site: 'Singapore Site A',
    crew: 'Shift Alpha',
    rotationStart: 'May 01, 2026',
    rotationEnd: 'May 15, 2026',
    status: 'on-duty',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    ticketStatus: 'Received',
  },
  {
    id: 'OPS-7781',
    name: 'Tom Harris',
    role: 'Field Technician',
    site: 'Dubai Site B',
    crew: 'Shift Beta',
    rotationStart: 'Jun 20, 2026',
    rotationEnd: 'Jul 04, 2026',
    status: 'off-duty',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop',
    ticketStatus: 'Not Received',
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: '1',
    type: 'arrival',
    message: 'Team arrival #TK-442 confirmed at destination.',
    time: '8 minutes ago',
    source: 'Coordination Desk',
    detail: '14 members checked into local housing.',
    status: 'normal',
  },
  {
    id: '2',
    type: 'visa',
    message: 'Visa approval for Sarah Jenkins.',
    time: '2 hours ago',
    source: 'Compliance Monitor',
    status: 'normal',
  },
  {
    id: '3',
    type: 'delay',
    message: 'Travel delay: Flight BA202 affecting 4 staff.',
    time: '4 hours ago',
    source: 'Transit Watch',
    detail: 'Schedule adjusted: +120 min.',
    status: 'critical',
  },
  {
    id: '4',
    type: 'rotation',
    message: 'New rotation starting: David Miller.',
    time: 'Yesterday, 17:45',
    source: 'Staff Manager',
    status: 'normal',
  },
];
